import {
  setA5Labels,
  setAnnotationLabels,
  setArcGisHubLabels,
  setBasemapControlLabels,
  setDggalLabels,
  setDggridLabels,
  setDimensionLabels,
  setEarthdataGisLabels,
  setGeoEditorLabels,
  setGeohashLabels,
  setGraticuleLabels,
  setH3Labels,
  setHuggingFaceLabels,
  setMapillaryLabels,
  setOlcLabels,
  setOpenAerialMapLabels,
  setOpenDataCatalogLabels,
  setReverseGeocodeLabels,
  setS2Labels,
  setS3BrowserLabels,
  setSamGeoLabels,
  setSourceCoopLabels,
  setStacLabels,
  setTennesseeGisLabels,
  setTilecodeLabels,
  setTimelapseLabels,
  setUsFederalGisLabels,
  setUsLocalGisLabels,
  setUsStateGisLabels,
  setUsgsDemLabels,
  setUsgsNldiLabels,
  type ArcGisHubLabels,
} from "@geolibre/plugins";
import { useEffect } from "react";
import { useTranslation } from "react-i18next";

/** Translation keys for the reasons a Zarr variable cannot be added. */
const ZARR_PROBLEM_KEYS = {
  group: "stacPlugin.zarrProblemGroup",
  missing: "stacPlugin.zarrProblemMissing",
  unauthorized: "stacPlugin.zarrProblemUnauthorized",
  "unsupported-url": "stacPlugin.zarrProblemUnsupportedUrl",
  unavailable: "stacPlugin.zarrProblemUnavailable",
} as const;

/**
 * Pushes translated strings into the built-in plugins and refreshes them
 * whenever the active language changes.
 *
 * The plugins live in the framework-agnostic plugins package and cannot call
 * t() themselves, so the toolbar (mounted for the whole authoring session)
 * hands them their labels.
 */
export function usePluginLabelSync(): void {
  const { t, i18n } = useTranslation();
  useEffect(() => {
    setReverseGeocodeLabels({
      lookingUp: t("geocode.reverseLookingUp"),
      noAddress: t("geocode.reverseNoAddress"),
      copyAddress: t("geocode.reverseCopyAddress"),
      failed: t("geocode.reverseFailed"),
    });
    setBasemapControlLabels({
      confirmStyleReplace: (name, count) => t("basemaps.confirmStyleReplace", { name, count }),
    });
    setAnnotationLabels({
      toolbar: t("annotations.toolbar"),
      collapse: t("sharedRail.collapse", { title: t("annotations.toolbar") }),
      expand: t("sharedRail.expand", { title: t("annotations.toolbar") }),
      layerName: t("annotations.layerName"),
      elementsPanelTitle: t("annotations.elementsPanelTitle"),
      tools: {
        text: t("annotations.tools.text"),
        arrow: t("annotations.tools.arrow"),
        rectangle: t("annotations.tools.rectangle"),
        ellipse: t("annotations.tools.ellipse"),
        freehand: t("annotations.tools.freehand"),
        pin: t("annotations.tools.pin"),
        sticky_note: t("annotations.tools.sticky_note"),
        placed_image: t("annotations.tools.placed_image"),
      },
      color: t("annotations.color"),
      width: t("annotations.width"),
      widthOptions: {
        thin: t("annotations.widthOptions.thin"),
        medium: t("annotations.widthOptions.medium"),
        thick: t("annotations.widthOptions.thick"),
      },
      deleteLast: t("annotations.deleteLast"),
      clearAll: t("annotations.clearAll"),
      newLayer: t("annotations.newLayer"),
      edit: t("annotations.edit"),
      move: t("annotations.move"),
      moveToLayer: t("annotations.moveToLayer"),
      textPlaceholder: t("annotations.textPlaceholder"),
      pinTitlePrompt: t("annotations.pinTitlePrompt"),
      pinDescPrompt: t("annotations.pinDescPrompt"),
      stickyNotePrompt: t("annotations.stickyNotePrompt"),
      imageUrlPrompt: t("annotations.imageUrlPrompt"),
      cancel: t("annotations.cancel"),
      saveElement: t("annotations.saveElement"),
      atPoint: t("annotations.atPoint"),
      pinnedToExtent: t("annotations.pinnedToExtent"),
      editorColor: t("annotations.editorColor"),
      noElements: t("annotations.noElements"),
      moveUp: t("annotations.moveUp"),
      moveDown: t("annotations.moveDown"),
      deleteElement: t("annotations.deleteElement"),
    });
    setDimensionLabels({
      toolbar: t("dimensions.toolbar"),
      collapse: t("sharedRail.collapse", { title: t("dimensions.toolbar") }),
      expand: t("sharedRail.expand", { title: t("dimensions.toolbar") }),
      layerName: t("dimensions.layerName"),
      tools: {
        linear: t("dimensions.tools.linear"),
        angular: t("dimensions.tools.angular"),
      },
      unit: t("dimensions.unit"),
      snap: t("dimensions.snap"),
      color: t("dimensions.color"),
      width: t("dimensions.width"),
      widthOptions: {
        thin: t("dimensions.widthOptions.thin"),
        medium: t("dimensions.widthOptions.medium"),
        thick: t("dimensions.widthOptions.thick"),
      },
      deleteLast: t("dimensions.deleteLast"),
      clearAll: t("dimensions.clearAll"),
      newLayer: t("dimensions.newLayer"),
      confirmClearAll: (count) => t("dimensions.confirmClearAll", { count }),
    });
    setMapillaryLabels({
      title: t("mapillary.title"),
      getTitle: () => i18n.t("mapillary.title"),
      hint: t("mapillary.hint"),
      noToken: t("mapillary.noToken"),
      tokenPlaceholder: t("mapillary.tokenPlaceholder"),
      tokenSave: t("mapillary.tokenSave"),
      tokenHelp: t("mapillary.tokenHelp"),
      tokenLabel: t("mapillary.tokenLabel"),
      loading: t("mapillary.loading"),
      loadError: t("mapillary.loadError"),
      coverageLines: t("mapillary.coverageLines"),
      coveragePoints: t("mapillary.coveragePoints"),
    });
    setOpenAerialMapLabels({
      hint: t("openAerialMap.hint"),
      search: t("openAerialMap.search"),
      loadMore: t("openAerialMap.loadMore"),
      searching: t("openAerialMap.searching"),
      loadingMore: t("openAerialMap.loadingMore"),
      noResults: t("openAerialMap.noResults"),
      showing: (shown, total) => t("openAerialMap.showing", { shown, total }),
      searchError: (message) => t("openAerialMap.searchError", { message }),
      add: t("openAerialMap.add"),
      remove: t("openAerialMap.remove"),
      zoom: t("openAerialMap.zoom"),
      download: t("openAerialMap.download"),
      metadata: t("openAerialMap.metadata"),
      addTitle: t("openAerialMap.addTitle"),
      removeTitle: t("openAerialMap.removeTitle"),
      addUnavailableTitle: t("openAerialMap.addUnavailableTitle"),
      zoomTitle: t("openAerialMap.zoomTitle"),
      downloadTitle: t("openAerialMap.downloadTitle"),
      metadataTitle: t("openAerialMap.metadataTitle"),
      modeView: t("openAerialMap.modeView"),
      modeDraw: t("openAerialMap.modeDraw"),
      modeBbox: t("openAerialMap.modeBbox"),
      drawHint: t("openAerialMap.drawHint"),
      drawStart: t("openAerialMap.drawStart"),
      drawCancel: t("openAerialMap.drawCancel"),
      drawnBox: (box) => t("openAerialMap.drawnBox", { box }),
      coordWest: t("openAerialMap.coordWest"),
      coordSouth: t("openAerialMap.coordSouth"),
      coordEast: t("openAerialMap.coordEast"),
      coordNorth: t("openAerialMap.coordNorth"),
      coordSearch: t("openAerialMap.coordSearch"),
      bboxInvalid: t("openAerialMap.bboxInvalid"),
      footprintsLayer: t("openAerialMap.footprintsLayer"),
      footprintUnavailable: t("openAerialMap.footprintUnavailable"),
      metadataHeading: t("openAerialMap.metadataHeading"),
      close: t("openAerialMap.close"),
      metaTitle: t("openAerialMap.metaTitle"),
      metaProvider: t("openAerialMap.metaProvider"),
      metaPlatform: t("openAerialMap.metaPlatform"),
      metaResolution: t("openAerialMap.metaResolution"),
      metaAcquired: t("openAerialMap.metaAcquired"),
      metaBounds: t("openAerialMap.metaBounds"),
      metaSource: t("openAerialMap.metaSource"),
      metaRaw: t("openAerialMap.metaRaw"),
    });
    const arcGisHubLabels: ArcGisHubLabels = {
      hint: t("arcgisHub.hint"),
      searchPlaceholder: t("arcgisHub.searchPlaceholder"),
      search: t("arcgisHub.search"),
      searchCurrentView: t("arcgisHub.searchCurrentView"),
      enterKeyword: t("arcgisHub.enterKeyword"),
      viewUnavailable: t("arcgisHub.viewUnavailable"),
      loadMore: t("arcgisHub.loadMore"),
      searching: t("arcgisHub.searching"),
      loadingMore: t("arcgisHub.loadingMore"),
      noResults: t("arcgisHub.noResults"),
      searchError: t("arcgisHub.searchError"),
      showing: (shown, total) => t("arcgisHub.showing", { shown, total }),
      showingSome: (shown) => t("arcgisHub.showingSome", { shown }),
      noDescription: t("arcgisHub.noDescription"),
      add: t("arcgisHub.add"),
      adding: (title) => t("arcgisHub.adding", { title }),
      added: (title) => t("arcgisHub.added", { title }),
      addedCapped: (title, limit) =>
        t("arcgisHub.addedCapped", {
          title,
          limit: limit.toLocaleString(i18n.language),
        }),
      addError: t("arcgisHub.addError"),
      zoom: t("arcgisHub.zoom"),
      download: t("arcgisHub.download"),
      preparing: (title) => t("arcgisHub.preparing", { title }),
      downloading: (completed, total, title) =>
        t("arcgisHub.downloading", { completed, total, title }),
      downloadStarted: (title) => t("arcgisHub.downloadStarted", { title }),
      downloadCapped: (title, limit) =>
        t("arcgisHub.downloadCapped", {
          title,
          limit: limit.toLocaleString(i18n.language),
        }),
      downloadFirstLayer: (title, layerCount) =>
        t("arcgisHub.downloadFirstLayer", { title, layerCount }),
      downloadError: t("arcgisHub.downloadError"),
      details: t("arcgisHub.details"),
    };
    setArcGisHubLabels(arcGisHubLabels);
    // The Tennessee portal is an ArcGIS Hub site, so it shares the panel's
    // strings and overrides only the ones that name the catalog.
    setTennesseeGisLabels({
      ...arcGisHubLabels,
      hint: t("tennesseeGis.hint"),
      searchPlaceholder: t("tennesseeGis.searchPlaceholder"),
      noResults: t("tennesseeGis.noResults"),
      searchError: t("tennesseeGis.searchError"),
    });
    setUsStateGisLabels({
      ...arcGisHubLabels,
      hint: t("usStateGis.hint"),
      searchPlaceholder: t("usStateGis.searchPlaceholder"),
      noResults: t("usStateGis.noResults"),
      searchError: t("usStateGis.searchError"),
      catalogSet: t("usStateGis.chooseState"),
      catalog: t("usStateGis.portal"),
      chooseCatalogSet: t("usStateGis.chooseStateHint"),
      openPortal: t("usStateGis.openPortal"),
    });
    setUsLocalGisLabels({
      ...arcGisHubLabels,
      hint: t("usLocalGis.hint"),
      searchPlaceholder: t("usLocalGis.searchPlaceholder"),
      noResults: t("usLocalGis.noResults"),
      searchError: t("usLocalGis.searchError"),
      catalogSet: t("usLocalGis.chooseState"),
      catalog: t("usLocalGis.portal"),
      chooseCatalogSet: t("usLocalGis.chooseStateHint"),
      openPortal: t("usLocalGis.openPortal"),
    });
    setUsFederalGisLabels({
      ...arcGisHubLabels,
      hint: t("usFederalGis.hint"),
      searchPlaceholder: t("usFederalGis.searchPlaceholder"),
      noResults: t("usFederalGis.noResults"),
      searchError: t("usFederalGis.searchError"),
      catalogSet: t("usFederalGis.chooseDepartment"),
      catalog: t("usFederalGis.agency"),
      chooseCatalogSet: t("usFederalGis.chooseDepartmentHint"),
      openPortal: t("usFederalGis.openPortal"),
    });
    setOpenDataCatalogLabels({
      socrataHint: t("openDataCatalogs.socrataHint"),
      ckanHint: t("openDataCatalogs.ckanHint"),
      searchPlaceholder: (name) => t("openDataCatalogs.searchPlaceholder", { name }),
      search: t("openDataCatalogs.search"),
      enterKeyword: t("openDataCatalogs.enterKeyword"),
      loadMore: t("openDataCatalogs.loadMore"),
      searching: t("openDataCatalogs.searching"),
      noResults: t("openDataCatalogs.noResults"),
      showing: (shown, total) => t("openDataCatalogs.showing", { shown, total }),
      noDescription: t("openDataCatalogs.noDescription"),
      add: t("openDataCatalogs.add"),
      details: t("openDataCatalogs.details"),
      adding: (title) => t("openDataCatalogs.adding", { title }),
      added: (title) => t("openDataCatalogs.added", { title }),
      addError: t("openDataCatalogs.addError"),
      searchError: t("openDataCatalogs.searchError"),
    });
    setEarthdataGisLabels({
      hint: t("earthdataGis.hint"),
      searchPlaceholder: t("earthdataGis.searchPlaceholder"),
      search: t("earthdataGis.search"),
      searching: t("earthdataGis.searching"),
      loadingMore: t("earthdataGis.loadingMore"),
      loadMore: t("earthdataGis.loadMore"),
      noResults: t("earthdataGis.noResults"),
      showing: (shown, total) => t("earthdataGis.showing", { shown, total }),
      searchError: (message) => t("earthdataGis.searchError", { message }),
      limitToView: t("earthdataGis.limitToView"),
      limitToViewTitle: t("earthdataGis.limitToViewTitle"),
      filterAll: t("earthdataGis.filterAll"),
      filterImage: t("earthdataGis.filterImage"),
      filterMap: t("earthdataGis.filterMap"),
      filterFeature: t("earthdataGis.filterFeature"),
      kindImage: t("earthdataGis.kindImage"),
      kindMap: t("earthdataGis.kindMap"),
      kindFeature: t("earthdataGis.kindFeature"),
      kindWebMap: t("earthdataGis.kindWebMap"),
      filterWebMap: t("earthdataGis.filterWebMap"),
      webMapAdded: (added, total) =>
        added === total
          ? t("earthdataGis.webMapAdded", { count: added })
          : t("earthdataGis.webMapAddedPartial", { added, total }),
      webMapEmpty: t("earthdataGis.webMapEmpty"),
      add: t("earthdataGis.add"),
      adding: t("earthdataGis.adding"),
      remove: t("earthdataGis.remove"),
      zoom: t("earthdataGis.zoom"),
      details: t("earthdataGis.details"),
      portal: t("earthdataGis.portal"),
      portalTitle: t("earthdataGis.portalTitle"),
      cog: t("earthdataGis.cog"),
      cogTitle: t("earthdataGis.cogTitle"),
      cogHeading: t("earthdataGis.cogHeading"),
      cogAreaView: t("earthdataGis.cogAreaView"),
      cogAreaExtent: t("earthdataGis.cogAreaExtent"),
      cogSize: (width, height) => t("earthdataGis.cogSize", { width, height }),
      cogResolution: (metres) => t("earthdataGis.cogResolution", { metres }),
      cogNote: t("earthdataGis.cogNote"),
      cogDownload: t("earthdataGis.cogDownload"),
      cogDownloading: t("earthdataGis.cogDownloading"),
      cogRetrying: (width, height) => t("earthdataGis.cogRetrying", { width, height }),
      cogConverting: t("earthdataGis.cogConverting"),
      cogDone: (width, height) => t("earthdataGis.cogDone", { width, height }),
      cogFailed: (message) => t("earthdataGis.cogFailed", { message }),
      cogUnavailable: t("earthdataGis.cogUnavailable"),
      cancel: t("earthdataGis.cancel"),
      addTitle: t("earthdataGis.addTitle"),
      removeTitle: t("earthdataGis.removeTitle"),
      zoomTitle: t("earthdataGis.zoomTitle"),
      zoomUnavailableTitle: t("earthdataGis.zoomUnavailableTitle"),
      detailsTitle: t("earthdataGis.detailsTitle"),
      addError: (message) => t("earthdataGis.addError", { message }),
      addTimeout: t("earthdataGis.addTimeout"),
      zoomedToData: t("earthdataGis.zoomedToData"),
      detailsHeading: t("earthdataGis.detailsHeading"),
      close: t("earthdataGis.close"),
      metaTitle: t("earthdataGis.metaTitle"),
      metaType: t("earthdataGis.metaType"),
      metaSummary: t("earthdataGis.metaSummary"),
      metaDescription: t("earthdataGis.metaDescription"),
      metaOwner: t("earthdataGis.metaOwner"),
      metaModified: t("earthdataGis.metaModified"),
      metaTags: t("earthdataGis.metaTags"),
      metaExtent: t("earthdataGis.metaExtent"),
      metaCredits: t("earthdataGis.metaCredits"),
      metaLicense: t("earthdataGis.metaLicense"),
      metaService: t("earthdataGis.metaService"),
      metaPortalItem: t("earthdataGis.metaPortalItem"),
      metaRaw: t("earthdataGis.metaRaw"),
    });
    setS3BrowserLabels({
      hint: t("s3Browser.hint"),
      noConnections: t("s3Browser.noConnections"),
      connection: t("s3Browser.connection"),
      listBuckets: t("s3Browser.listBuckets"),
      locationPlaceholder: t("s3Browser.locationPlaceholder"),
      go: t("s3Browser.go"),
      up: t("s3Browser.up"),
      loading: t("s3Browser.loading"),
      empty: t("s3Browser.empty"),
      loadMore: t("s3Browser.loadMore"),
      add: t("s3Browser.add"),
      added: t("s3Browser.added"),
      adding: t("s3Browser.adding"),
      copyUri: t("s3Browser.copyUri"),
      copied: t("s3Browser.copied"),
      tooLarge: t("s3Browser.tooLarge"),
      notAddable: t("s3Browser.notAddable"),
      signed: t("s3Browser.signed"),
      anonymous: t("s3Browser.anonymous"),
      setDefault: t("s3Browser.setDefault"),
      isDefault: t("s3Browser.isDefault"),
      pointCloud: t("s3Browser.pointCloud"),
      select: t("s3Browser.select"),
      selectAll: t("s3Browser.selectAll"),
      addSelected: (count) => t("s3Browser.addSelected", { count }),
      addingProgress: (index, total) => t("s3Browser.addingProgress", { index, total }),
      addFailed: (name, message) => t("s3Browser.addFailed", { name, message }),
      error: (message) => t("s3Browser.error", { message }),
    });
    setSourceCoopLabels({
      hint: t("sourceCoop.hint"),
      searchPlaceholder: t("sourceCoop.searchPlaceholder"),
      search: t("sourceCoop.search"),
      searching: t("sourceCoop.searching"),
      loading: t("sourceCoop.loading"),
      loadError: (message) => t("sourceCoop.loadError", { message }),
      noResults: t("sourceCoop.noResults"),
      retry: t("sourceCoop.retry"),
      featured: t("sourceCoop.featured"),
      showing: (shown, total) => t("sourceCoop.showing", { shown, total }),
      browseAccount: (account) => t("sourceCoop.browseAccount", { account }),
      back: t("sourceCoop.back"),
      files: t("sourceCoop.files"),
      noFiles: t("sourceCoop.noFiles"),
      loadingFiles: t("sourceCoop.loadingFiles"),
      loadMore: t("sourceCoop.loadMore"),
      parent: t("sourceCoop.parent"),
      add: t("sourceCoop.add"),
      adding: t("sourceCoop.adding"),
      added: t("sourceCoop.added"),
      stream: t("sourceCoop.stream"),
      streaming: t("sourceCoop.streaming"),
      remove: t("sourceCoop.remove"),
      download: t("sourceCoop.download"),
      copyUrl: t("sourceCoop.copyUrl"),
      copied: t("sourceCoop.copied"),
      openProduct: t("sourceCoop.openProduct"),
      addTitle: t("sourceCoop.addTitle"),
      streamTitle: t("sourceCoop.streamTitle"),
      removeTitle: t("sourceCoop.removeTitle"),
      downloadTitle: t("sourceCoop.downloadTitle"),
      copyUrlTitle: t("sourceCoop.copyUrlTitle"),
      openProductTitle: t("sourceCoop.openProductTitle"),
      unsupportedTitle: t("sourceCoop.unsupportedTitle"),
      addError: (message) => t("sourceCoop.addError", { message }),
      largeFileWarning: (size) => t("sourceCoop.largeFileWarning", { size }),
      streamHint: (size) => t("sourceCoop.streamHint", { size }),
      tooLargeToOpen: (size, limit) => t("sourceCoop.tooLargeToOpen", { size, limit }),
    });
    setHuggingFaceLabels({
      browseTab: t("huggingFace.browseTab"),
      uploadTab: t("huggingFace.uploadTab"),
      settingsTab: t("huggingFace.settingsTab"),
      hint: t("huggingFace.hint"),
      searchPlaceholder: t("huggingFace.searchPlaceholder"),
      search: t("huggingFace.search"),
      searching: t("huggingFace.searching"),
      loadError: (message) => t("huggingFace.loadError", { message }),
      noResults: t("huggingFace.noResults"),
      retry: t("huggingFace.retry"),
      suggestions: t("huggingFace.suggestions"),
      showing: (count) => t("huggingFace.showing", { count }),
      browseOwner: (owner) => t("huggingFace.browseOwner", { owner }),
      back: t("huggingFace.back"),
      private: t("huggingFace.private"),
      gated: t("huggingFace.gated"),
      privateHint: t("huggingFace.privateHint"),
      stats: (likes, downloads) => t("huggingFace.stats", { likes, downloads }),
      noFiles: t("huggingFace.noFiles"),
      loadingFiles: t("huggingFace.loadingFiles"),
      loadMore: t("huggingFace.loadMore"),
      parent: t("huggingFace.parent"),
      add: t("huggingFace.add"),
      adding: t("huggingFace.adding"),
      stream: t("huggingFace.stream"),
      streaming: t("huggingFace.streaming"),
      remove: t("huggingFace.remove"),
      download: t("huggingFace.download"),
      copyUrl: t("huggingFace.copyUrl"),
      copied: t("huggingFace.copied"),
      openDataset: t("huggingFace.openDataset"),
      addTitle: t("huggingFace.addTitle"),
      streamTitle: t("huggingFace.streamTitle"),
      removeTitle: t("huggingFace.removeTitle"),
      downloadTitle: t("huggingFace.downloadTitle"),
      copyUrlTitle: t("huggingFace.copyUrlTitle"),
      openDatasetTitle: t("huggingFace.openDatasetTitle"),
      unsupportedTitle: t("huggingFace.unsupportedTitle"),
      addError: (message) => t("huggingFace.addError", { message }),
      notRasterIndex: t("huggingFace.notRasterIndex"),
      largeFileWarning: (size) => t("huggingFace.largeFileWarning", { size }),
      streamHint: (size) => t("huggingFace.streamHint", { size }),
      tooLargeToOpen: (size, limit) => t("huggingFace.tooLargeToOpen", { size, limit }),
      tokenLabel: t("huggingFace.tokenLabel"),
      tokenHint: t("huggingFace.tokenHint"),
      tokenHintKeychain: t("huggingFace.tokenHintKeychain"),
      tokenPlaceholder: t("huggingFace.tokenPlaceholder"),
      tokenSave: t("huggingFace.tokenSave"),
      tokenClear: t("huggingFace.tokenClear"),
      tokenHelp: t("huggingFace.tokenHelp"),
      tokenChecking: t("huggingFace.tokenChecking"),
      tokenError: (message) => t("huggingFace.tokenError", { message }),
      signedInAs: (name) => t("huggingFace.signedInAs", { name }),
      readOnlyToken: t("huggingFace.readOnlyToken"),
      createHeading: t("huggingFace.createHeading"),
      ownerLabel: t("huggingFace.ownerLabel"),
      datasetNameLabel: t("huggingFace.datasetNameLabel"),
      datasetNamePlaceholder: t("huggingFace.datasetNamePlaceholder"),
      privateLabel: t("huggingFace.privateLabel"),
      create: t("huggingFace.create"),
      creating: t("huggingFace.creating"),
      createdRepo: (repoId) => t("huggingFace.createdRepo", { repoId }),
      createError: (message) => t("huggingFace.createError", { message }),
      uploadHeading: t("huggingFace.uploadHeading"),
      targetLabel: t("huggingFace.targetLabel"),
      targetPlaceholder: t("huggingFace.targetPlaceholder"),
      folderLabel: t("huggingFace.folderLabel"),
      folderPlaceholder: t("huggingFace.folderPlaceholder"),
      chooseFiles: t("huggingFace.chooseFiles"),
      chooseLayer: t("huggingFace.chooseLayer"),
      chooseLayerTitle: t("huggingFace.chooseLayerTitle"),
      layerPickerHeading: t("huggingFace.layerPickerHeading"),
      layerFeatures: (count) => t("huggingFace.layerFeatures", { count }),
      layerOriginalFile: t("huggingFace.layerOriginalFile"),
      layerUnavailable: (name) => t("huggingFace.layerUnavailable", { name }),
      remoteRasterNote: t("huggingFace.remoteRasterNote"),
      noUploadableLayers: t("huggingFace.noUploadableLayers"),
      clearSelection: t("huggingFace.clearSelection"),
      selectedFiles: (count, size) => t("huggingFace.selectedFiles", { count, size }),
      commitMessageLabel: t("huggingFace.commitMessageLabel"),
      commitMessagePlaceholder: t("huggingFace.commitMessagePlaceholder"),
      upload: t("huggingFace.upload"),
      uploadPreparing: t("huggingFace.uploadPreparing"),
      uploadHashing: (name, index, total) => t("huggingFace.uploadHashing", { name, index, total }),
      uploadSending: (name, index, total) => t("huggingFace.uploadSending", { name, index, total }),
      uploadCommitting: t("huggingFace.uploadCommitting"),
      uploadDone: (count) => t("huggingFace.uploadDone", { count }),
      uploadError: (message) => t("huggingFace.uploadError", { message }),
      fileTooLarge: (name, limit) => t("huggingFace.fileTooLarge", { name, limit }),
      selectionTooLarge: (size, limit) => t("huggingFace.selectionTooLarge", { size, limit }),
      openUploaded: t("huggingFace.openUploaded"),
      rgbHeading: t("huggingFace.rgbHeading"),
      rgbHint: t("huggingFace.rgbHint"),
      bandR: t("huggingFace.bandR"),
      bandG: t("huggingFace.bandG"),
      bandB: t("huggingFace.bandB"),
      colormapHeading: t("huggingFace.colormapHeading"),
      colormapHint: t("huggingFace.colormapHint"),
      colormapLabel: t("huggingFace.colormapLabel"),
      engineHeading: t("huggingFace.engineHeading"),
      engineHint: t("huggingFace.engineHint"),
      engineLabel: t("huggingFace.engineLabel"),
      engineAuto: t("huggingFace.engineAuto"),
      engineGpu: t("huggingFace.engineGpu"),
      engineWasm: t("huggingFace.engineWasm"),
      engineTitiler: t("huggingFace.engineTitiler"),
      resetDefaults: t("huggingFace.resetDefaults"),
    });
    setGeoEditorLabels({
      attributePanelTitle: t("geoEditorPlugin.attributePanelTitle"),
      massingHeight: t("geoEditorPlugin.massingHeight"),
    });
    setGraticuleLabels({
      title: t("graticule.title"),
      getTitle: () => i18n.t("graticule.title"),
      controlTitle: t("graticule.controlTitle"),
      gridType: t("graticule.gridType"),
      typeGeographic: t("graticule.typeGeographic"),
      typeUtm: t("graticule.typeUtm"),
      spacing: t("graticule.spacing"),
      spacingAuto: t("graticule.spacingAuto"),
      spacingFixed: t("graticule.spacingFixed"),
      interval: t("graticule.interval"),
      intervalMeters: t("graticule.intervalMeters"),
      lineColor: t("graticule.lineColor"),
      lineWidth: t("graticule.lineWidth"),
      lineOpacity: t("graticule.lineOpacity"),
      dashedLines: t("graticule.dashedLines"),
      showLabels: t("graticule.showLabels"),
      labelFormat: t("graticule.labelFormat"),
      formatDecimal: t("graticule.formatDecimal"),
      formatDms: t("graticule.formatDms"),
      labelEdges: t("graticule.labelEdges"),
      edgesLeftBottom: t("graticule.edgesLeftBottom"),
      edgesAll: t("graticule.edgesAll"),
      labelColor: t("graticule.labelColor"),
      labelSize: t("graticule.labelSize"),
    });
    setH3Labels({
      title: t("h3Plugin.title"),
      getTitle: () => i18n.t("h3Plugin.title"),
      controlTitle: t("h3Plugin.controlTitle"),
      autoResolution: t("h3Plugin.autoResolution"),
      resolution: t("h3Plugin.resolution"),
      cellCount: (count) => t("h3Plugin.cellCount", { count }),
      tooManyCells: (limit) => t("h3Plugin.tooManyCells", { limit }),
      fillColor: t("h3Plugin.fillColor"),
      fillOpacity: t("h3Plugin.fillOpacity"),
      lineColor: t("h3Plugin.lineColor"),
      lineWidth: t("h3Plugin.lineWidth"),
      showLabels: t("h3Plugin.showLabels"),
      identifyHint: t("h3Plugin.identifyHint"),
      selectedCell: t("h3Plugin.selectedCell"),
      noSelection: t("h3Plugin.noSelection"),
      copyId: t("h3Plugin.copyId"),
      copied: t("h3Plugin.copied"),
      parent: t("h3Plugin.parent"),
      children: t("h3Plugin.children"),
      neighbors: t("h3Plugin.neighbors"),
      baseCell: t("h3Plugin.baseCell"),
      center: t("h3Plugin.center"),
      pentagon: t("h3Plugin.pentagon"),
      yes: t("h3Plugin.yes"),
      no: t("h3Plugin.no"),
      zoomToCell: t("h3Plugin.zoomToCell"),
      addAsLayer: t("h3Plugin.addAsLayer"),
      exportGeoJson: t("h3Plugin.exportGeoJson"),
      exportCsv: t("h3Plugin.exportCsv"),
      includeNeighbors: t("h3Plugin.includeNeighbors"),
      includeParents: t("h3Plugin.includeParents"),
      showIcosahedron: t("h3Plugin.showIcosahedron"),
    });
    setS2Labels({
      title: t("s2Plugin.title"),
      getTitle: () => i18n.t("s2Plugin.title"),
      controlTitle: t("s2Plugin.controlTitle"),
      autoResolution: t("s2Plugin.autoResolution"),
      resolution: t("s2Plugin.resolution"),
      cellCount: (count) => t("s2Plugin.cellCount", { count }),
      tooManyCells: (limit) => t("s2Plugin.tooManyCells", { limit }),
      fillColor: t("s2Plugin.fillColor"),
      fillOpacity: t("s2Plugin.fillOpacity"),
      lineColor: t("s2Plugin.lineColor"),
      lineWidth: t("s2Plugin.lineWidth"),
      showLabels: t("s2Plugin.showLabels"),
      identifyHint: t("s2Plugin.identifyHint"),
      selectedCell: t("s2Plugin.selectedCell"),
      noSelection: t("s2Plugin.noSelection"),
      copyId: t("s2Plugin.copyId"),
      parent: t("s2Plugin.parent"),
      children: t("s2Plugin.children"),
      neighbors: t("s2Plugin.neighbors"),
      center: t("s2Plugin.center"),
      zoomToCell: t("s2Plugin.zoomToCell"),
      addAsLayer: t("s2Plugin.addAsLayer"),
      exportGeoJson: t("s2Plugin.exportGeoJson"),
      exportCsv: t("s2Plugin.exportCsv"),
      includeNeighbors: t("s2Plugin.includeNeighbors"),
      includeParents: t("s2Plugin.includeParents"),
    });
    setA5Labels({
      title: t("a5Plugin.title"),
      getTitle: () => i18n.t("a5Plugin.title"),
      controlTitle: t("a5Plugin.controlTitle"),
      autoResolution: t("a5Plugin.autoResolution"),
      resolution: t("a5Plugin.resolution"),
      cellCount: (count) => t("a5Plugin.cellCount", { count }),
      tooManyCells: (limit) => t("a5Plugin.tooManyCells", { limit }),
      fillColor: t("a5Plugin.fillColor"),
      fillOpacity: t("a5Plugin.fillOpacity"),
      lineColor: t("a5Plugin.lineColor"),
      lineWidth: t("a5Plugin.lineWidth"),
      showLabels: t("a5Plugin.showLabels"),
      identifyHint: t("a5Plugin.identifyHint"),
      selectedCell: t("a5Plugin.selectedCell"),
      noSelection: t("a5Plugin.noSelection"),
      copyId: t("a5Plugin.copyId"),
      parent: t("a5Plugin.parent"),
      children: t("a5Plugin.children"),
      neighbors: t("a5Plugin.neighbors"),
      center: t("a5Plugin.center"),
      zoomToCell: t("a5Plugin.zoomToCell"),
      addAsLayer: t("a5Plugin.addAsLayer"),
      exportGeoJson: t("a5Plugin.exportGeoJson"),
      exportCsv: t("a5Plugin.exportCsv"),
      includeNeighbors: t("a5Plugin.includeNeighbors"),
      includeParents: t("a5Plugin.includeParents"),
    });
    setDggridLabels({
      title: t("dggridPlugin.title"),
      getTitle: () => i18n.t("dggridPlugin.title"),
      controlTitle: t("dggridPlugin.controlTitle"),
      cellType: t("dggridPlugin.cellType"),
      topologyHexagon: t("dggridPlugin.topologyHexagon"),
      topologyDiamond: t("dggridPlugin.topologyDiamond"),
      topologyTriangle: t("dggridPlugin.topologyTriangle"),
      projection: t("dggridPlugin.projection"),
      aperture: t("dggridPlugin.aperture"),
      autoResolution: t("dggridPlugin.autoResolution"),
      resolution: t("dggridPlugin.resolution"),
      cellCount: (count) => t("dggridPlugin.cellCount", { count }),
      tooManyCells: (limit) => t("dggridPlugin.tooManyCells", { limit }),
      fillColor: t("dggridPlugin.fillColor"),
      fillOpacity: t("dggridPlugin.fillOpacity"),
      lineColor: t("dggridPlugin.lineColor"),
      lineWidth: t("dggridPlugin.lineWidth"),
      showLabels: t("dggridPlugin.showLabels"),
      identifyHint: t("dggridPlugin.identifyHint"),
      selectedCell: t("dggridPlugin.selectedCell"),
      noSelection: t("dggridPlugin.noSelection"),
      copyId: t("dggridPlugin.copyId"),
      parent: t("dggridPlugin.parent"),
      children: t("dggridPlugin.children"),
      neighbors: t("dggridPlugin.neighbors"),
      center: t("dggridPlugin.center"),
      zoomToCell: t("dggridPlugin.zoomToCell"),
      addAsLayer: t("dggridPlugin.addAsLayer"),
      exportGeoJson: t("dggridPlugin.exportGeoJson"),
      exportCsv: t("dggridPlugin.exportCsv"),
      includeNeighbors: t("dggridPlugin.includeNeighbors"),
      includeParents: t("dggridPlugin.includeParents"),
    });
    setDggalLabels({
      title: t("dggalPlugin.title"),
      getTitle: () => i18n.t("dggalPlugin.title"),
      controlTitle: t("dggalPlugin.controlTitle"),
      gridType: t("dggalPlugin.gridType"),
      autoResolution: t("dggalPlugin.autoResolution"),
      resolution: t("dggalPlugin.resolution"),
      cellCount: (count) => t("dggalPlugin.cellCount", { count }),
      tooManyCells: (limit) => t("dggalPlugin.tooManyCells", { limit }),
      fillColor: t("dggalPlugin.fillColor"),
      fillOpacity: t("dggalPlugin.fillOpacity"),
      lineColor: t("dggalPlugin.lineColor"),
      lineWidth: t("dggalPlugin.lineWidth"),
      showLabels: t("dggalPlugin.showLabels"),
      identifyHint: t("dggalPlugin.identifyHint"),
      selectedCell: t("dggalPlugin.selectedCell"),
      noSelection: t("dggalPlugin.noSelection"),
      copyId: t("dggalPlugin.copyId"),
      parent: t("dggalPlugin.parent"),
      children: t("dggalPlugin.children"),
      neighbors: t("dggalPlugin.neighbors"),
      center: t("dggalPlugin.center"),
      zoomToCell: t("dggalPlugin.zoomToCell"),
      addAsLayer: t("dggalPlugin.addAsLayer"),
      exportGeoJson: t("dggalPlugin.exportGeoJson"),
      exportCsv: t("dggalPlugin.exportCsv"),
      includeNeighbors: t("dggalPlugin.includeNeighbors"),
      includeParents: t("dggalPlugin.includeParents"),
    });
    setOlcLabels({
      title: t("olcPlugin.title"),
      getTitle: () => i18n.t("olcPlugin.title"),
      controlTitle: t("olcPlugin.controlTitle"),
      autoResolution: t("olcPlugin.autoResolution"),
      resolution: t("olcPlugin.resolution"),
      cellCount: (count) => t("olcPlugin.cellCount", { count }),
      tooManyCells: (limit) => t("olcPlugin.tooManyCells", { limit }),
      fillColor: t("olcPlugin.fillColor"),
      fillOpacity: t("olcPlugin.fillOpacity"),
      lineColor: t("olcPlugin.lineColor"),
      lineWidth: t("olcPlugin.lineWidth"),
      showLabels: t("olcPlugin.showLabels"),
      identifyHint: t("olcPlugin.identifyHint"),
      selectedCell: t("olcPlugin.selectedCell"),
      noSelection: t("olcPlugin.noSelection"),
      copyId: t("olcPlugin.copyId"),
      parent: t("olcPlugin.parent"),
      children: t("olcPlugin.children"),
      neighbors: t("olcPlugin.neighbors"),
      center: t("olcPlugin.center"),
      zoomToCell: t("olcPlugin.zoomToCell"),
      addAsLayer: t("olcPlugin.addAsLayer"),
      exportGeoJson: t("olcPlugin.exportGeoJson"),
      exportCsv: t("olcPlugin.exportCsv"),
      includeNeighbors: t("olcPlugin.includeNeighbors"),
      includeParent: t("olcPlugin.includeParent"),
    });
    setGeohashLabels({
      title: t("geohashPlugin.title"),
      getTitle: () => i18n.t("geohashPlugin.title"),
      controlTitle: t("geohashPlugin.controlTitle"),
      autoResolution: t("geohashPlugin.autoResolution"),
      resolution: t("geohashPlugin.resolution"),
      cellCount: (count) => t("geohashPlugin.cellCount", { count }),
      tooManyCells: (limit) => t("geohashPlugin.tooManyCells", { limit }),
      fillColor: t("geohashPlugin.fillColor"),
      fillOpacity: t("geohashPlugin.fillOpacity"),
      lineColor: t("geohashPlugin.lineColor"),
      lineWidth: t("geohashPlugin.lineWidth"),
      showLabels: t("geohashPlugin.showLabels"),
      identifyHint: t("geohashPlugin.identifyHint"),
      selectedCell: t("geohashPlugin.selectedCell"),
      noSelection: t("geohashPlugin.noSelection"),
      copyId: t("geohashPlugin.copyId"),
      parent: t("geohashPlugin.parent"),
      children: t("geohashPlugin.children"),
      neighbors: t("geohashPlugin.neighbors"),
      center: t("geohashPlugin.center"),
      zoomToCell: t("geohashPlugin.zoomToCell"),
      addAsLayer: t("geohashPlugin.addAsLayer"),
      exportGeoJson: t("geohashPlugin.exportGeoJson"),
      exportCsv: t("geohashPlugin.exportCsv"),
      includeNeighbors: t("geohashPlugin.includeNeighbors"),
      includeParent: t("geohashPlugin.includeParent"),
    });
    setUsgsNldiLabels({
      panelTitle: t("usgsNldi.panelTitle"),
      title: t("usgsNldi.title"),
      hint: t("usgsNldi.hint"),
      directionComplete: t("usgsNldi.directionComplete"),
      directionUp: t("usgsNldi.directionUp"),
      directionDown: t("usgsNldi.directionDown"),
      basinButton: t("usgsNldi.basinButton"),
      navigationPlaceholder: t("usgsNldi.navigationPlaceholder"),
      navigationUpstreamMain: t("usgsNldi.navigationUpstreamMain"),
      navigationUpstreamTributaries: t("usgsNldi.navigationUpstreamTributaries"),
      navigationDownstreamMain: t("usgsNldi.navigationDownstreamMain"),
      navigationDownstreamDiversions: t("usgsNldi.navigationDownstreamDiversions"),
      sourcePlaceholder: t("usgsNldi.sourcePlaceholder"),
      distancePlaceholder: t("usgsNldi.distancePlaceholder"),
      navigationButton: t("usgsNldi.navigationButton"),
      navigationButtonAgain: t("usgsNldi.navigationButtonAgain"),
      exportButton: t("usgsNldi.exportButton"),
      addLayersButton: t("usgsNldi.addLayersButton"),
      clearButton: t("usgsNldi.clearButton"),
      noComid: t("usgsNldi.noComid"),
      requestingBasin: t("usgsNldi.requestingBasin"),
      basinRendered: (comid) => t("usgsNldi.basinRendered", { comid }),
      basinFailed: t("usgsNldi.basinFailed"),
      selectNavigation: t("usgsNldi.selectNavigation"),
      invalidDistance: t("usgsNldi.invalidDistance"),
      discoveringSources: t("usgsNldi.discoveringSources"),
      navigationUnavailable: t("usgsNldi.navigationUnavailable"),
      noPlottableSource: t("usgsNldi.noPlottableSource"),
      navigationEmpty: (source) => t("usgsNldi.navigationEmpty", { source }),
      navigationAdded: (source, navigation, comid, km) =>
        t("usgsNldi.navigationAdded", { source, navigation, comid, km }),
      navigationFailed: t("usgsNldi.navigationFailed"),
      tracing: t("usgsNldi.tracing"),
      flowlineRendered: (comid, usedFallback) =>
        comid
          ? t(usedFallback ? "usgsNldi.flowlineFallbackComid" : "usgsNldi.flowlineComid", { comid })
          : t(usedFallback ? "usgsNldi.flowlineFallback" : "usgsNldi.flowline"),
      requestFailed: t("usgsNldi.requestFailed"),
      nothingToAdd: t("usgsNldi.nothingToAdd"),
      layersAdded: (count) => t("usgsNldi.layersAdded", { count }),
      layerGroupName: t("usgsNldi.layerGroupName"),
      layerFlowline: t("usgsNldi.layerFlowline"),
      layerRaindrop: t("usgsNldi.layerRaindrop"),
      layerSelectedPoint: t("usgsNldi.layerSelectedPoint"),
      layerBasin: t("usgsNldi.layerBasin"),
      layerNavigation: (index) => t("usgsNldi.layerNavigation", { index }),
      resultCleared: t("usgsNldi.resultCleared"),
      directionalUnavailable: t("usgsNldi.directionalUnavailable"),
      noFlowlineNearby: t("usgsNldi.noFlowlineNearby"),
      httpError: (status, detail) =>
        detail
          ? t("usgsNldi.httpErrorDetail", { status, detail })
          : t("usgsNldi.httpError", { status }),
      noAttributes: t("usgsNldi.noAttributes"),
      catalogNames: {
        ca_gages: t("usgsNldi.catalogCaGages"),
        nwissite: t("usgsNldi.catalogNwisSite"),
        nwisgw: t("usgsNldi.catalogNwisGw"),
        gfv11_pois: t("usgsNldi.catalogGfv11Pois"),
        huc12pp: t("usgsNldi.catalogHuc12pp"),
        "nmwdi-st": t("usgsNldi.catalogNmwdiSt"),
        flowlines: t("usgsNldi.catalogFlowlines"),
      },
    });
    setUsgsDemLabels({
      title: t("usgsDem.title"),
      hint: t("usgsDem.hint"),
      search: t("usgsDem.search"),
      searching: t("usgsDem.searching"),
      noResults: t("usgsDem.noResults"),
      add: t("usgsDem.add"),
      adding: t("usgsDem.adding"),
      download: t("usgsDem.download"),
      zoom: t("usgsDem.zoom"),
      modeView: t("usgsDem.modeView"),
      modeDraw: t("usgsDem.modeDraw"),
      modeBbox: t("usgsDem.modeBbox"),
      modeQuad: t("usgsDem.modeQuad"),
      drawHint: t("usgsDem.drawHint"),
      drawStart: t("usgsDem.drawStart"),
      drawCancel: t("usgsDem.drawCancel"),
      coordWest: t("usgsDem.coordWest"),
      coordSouth: t("usgsDem.coordSouth"),
      coordEast: t("usgsDem.coordEast"),
      coordNorth: t("usgsDem.coordNorth"),
      quadName: t("usgsDem.quadName"),
      stateName: t("usgsDem.stateName"),
      quadSearchHint: t("usgsDem.quadSearchHint"),
      datasets: t("usgsDem.datasets"),
      format: t("usgsDem.format"),
      filterRedundant: t("usgsDem.filterRedundant"),
      footprintsLayer: t("usgsDem.footprintsLayer"),
      exportGeoJson: t("usgsDem.exportGeoJson"),
      errorNoBounds: t("usgsDem.errorNoBounds"),
      errorNoDrawnBox: t("usgsDem.errorNoDrawnBox"),
      errorInvalidCoords: t("usgsDem.errorInvalidCoords"),
      errorQuadInputs: t("usgsDem.errorQuadInputs"),
      showing: (shown, total) => t("usgsDem.showing", { shown, total }),
      searchError: (message) => t("usgsDem.searchError", { message }),
      drawnBox: (box) => t("usgsDem.drawnBox", { box }),
      errorQuadNotFound: (quad, state) => t("usgsDem.errorQuadNotFound", { quad, state }),
      loadError: (message) => t("usgsDem.loadError", { message }),
    });
    setTilecodeLabels({
      title: t("tilecodePlugin.title"),
      getTitle: () => i18n.t("tilecodePlugin.title"),
      controlTitle: t("tilecodePlugin.controlTitle"),
      autoResolution: t("tilecodePlugin.autoResolution"),
      resolution: t("tilecodePlugin.resolution"),
      cellCount: (count) => t("tilecodePlugin.cellCount", { count }),
      tooManyCells: (limit) => t("tilecodePlugin.tooManyCells", { limit }),
      fillColor: t("tilecodePlugin.fillColor"),
      fillOpacity: t("tilecodePlugin.fillOpacity"),
      lineColor: t("tilecodePlugin.lineColor"),
      lineWidth: t("tilecodePlugin.lineWidth"),
      showLabels: t("tilecodePlugin.showLabels"),
      identifyHint: t("tilecodePlugin.identifyHint"),
      selectedCell: t("tilecodePlugin.selectedCell"),
      noSelection: t("tilecodePlugin.noSelection"),
      copyId: t("tilecodePlugin.copyId"),
      quadkey: t("tilecodePlugin.quadkey"),
      parent: t("tilecodePlugin.parent"),
      children: t("tilecodePlugin.children"),
      neighbors: t("tilecodePlugin.neighbors"),
      center: t("tilecodePlugin.center"),
      zoomToCell: t("tilecodePlugin.zoomToCell"),
      addAsLayer: t("tilecodePlugin.addAsLayer"),
      exportGeoJson: t("tilecodePlugin.exportGeoJson"),
      exportCsv: t("tilecodePlugin.exportCsv"),
      includeNeighbors: t("tilecodePlugin.includeNeighbors"),
      includeParent: t("tilecodePlugin.includeParent"),
    });
    setTimelapseLabels({
      title: t("timelapse.title"),
      provider: t("timelapse.provider"),
      legend: t("timelapse.legend"),
      yearSlider: t("timelapse.yearSlider"),
      play: t("timelapse.play"),
      pause: t("timelapse.pause"),
      speed: t("timelapse.speed"),
      secondsPerYear: t("timelapse.secondsPerYear"),
      secondsPerYearSuffix: t("timelapse.secondsPerYearSuffix"),
      loop: t("timelapse.loop"),
      record: t("timelapse.record"),
      stopRecording: t("timelapse.stopRecording"),
      recording: t("timelapse.recording"),
      recordingFailed: t("timelapse.recordingFailed"),
      recordingUnsupported: t("timelapse.recordingUnsupported"),
      loadingTiles: t("timelapse.loadingTiles"),
    });
    setStacLabels({
      title: t("stacPlugin.title"),
      getTitle: () => i18n.t("stacPlugin.title"),
      planetTitle: t("toolbar.plugin.geolibre-planet-open-data"),
      getPlanetTitle: () => i18n.t("toolbar.plugin.geolibre-planet-open-data"),
      footprintLayerName: t("stacPlugin.footprintLayerName"),
      catalogSearch: t("stacPlugin.catalogSearch"),
      catalogSearchPlaceholder: t("stacPlugin.catalogSearchPlaceholder"),
      indexLoading: t("stacPlugin.indexLoading"),
      indexUnavailable: t("stacPlugin.indexUnavailable"),
      indexLoadFailed: t("stacPlugin.indexLoadFailed"),
      urlLabel: t("stacPlugin.urlLabel"),
      connect: t("stacPlugin.connect"),
      connecting: t("stacPlugin.connecting"),
      connected: t("stacPlugin.connected"),
      connectFailed: t("stacPlugin.connectFailed"),
      selectCatalog: t("stacPlugin.selectCatalog"),
      noMatchingCatalogs: t("stacPlugin.noMatchingCatalogs"),
      catalogApiSuffix: t("stacPlugin.catalogApiSuffix"),
      catalogStaticSuffix: t("stacPlugin.catalogStaticSuffix"),
      kindApi: t("stacPlugin.kindApi"),
      kindStatic: t("stacPlugin.kindStatic"),
      collectionsHint: t("stacPlugin.collectionsHint"),
      limitToExtent: t("stacPlugin.limitToExtent"),
      bboxLabel: t("stacPlugin.bboxLabel"),
      bboxPlaceholder: t("stacPlugin.bboxPlaceholder"),
      bboxInvalid: t("stacPlugin.bboxInvalid"),
      drawBbox: t("stacPlugin.drawBbox"),
      cancelDrawing: t("stacPlugin.cancelDrawing"),
      clearDrawnBbox: t("stacPlugin.clearDrawnBbox"),
      drawHint: t("stacPlugin.drawHint"),
      drawnBbox: (bbox) => t("stacPlugin.drawnBbox", { bbox }),
      drawnBboxCleared: t("stacPlugin.drawnBboxCleared"),
      mapNotReady: t("stacPlugin.mapNotReady"),
      startDate: t("stacPlugin.startDate"),
      endDate: t("stacPlugin.endDate"),
      additionalParams: t("stacPlugin.additionalParams"),
      additionalInvalid: t("stacPlugin.additionalInvalid"),
      searchItems: t("stacPlugin.searchItems"),
      clearResults: t("stacPlugin.clearResults"),
      resultsCleared: t("stacPlugin.resultsCleared"),
      searching: t("stacPlugin.searching"),
      loadingMore: t("stacPlugin.loadingMore"),
      noMatchesHere: t("stacPlugin.noMatchesHere"),
      treeEmpty: t("stacPlugin.treeEmpty"),
      treeOpenFailed: t("stacPlugin.treeOpenFailed"),
      noResults: t("stacPlugin.noResults"),
      searchFailed: t("stacPlugin.searchFailed"),
      showing: (count) => t("stacPlugin.showing", { count }),
      showingOfMatched: (count, matched) => t("stacPlugin.showingOfMatched", { count, matched }),
      loadMore: t("stacPlugin.loadMore"),
      renderOptions: t("stacPlugin.renderOptions"),
      renderingEngine: t("stacPlugin.renderingEngine"),
      engineAuto: t("stacPlugin.engineAuto"),
      engineGpu: t("stacPlugin.engineGpu"),
      engineWasm: t("stacPlugin.engineWasm"),
      engineTitiler: t("stacPlugin.engineTitiler"),
      engineHint: t("stacPlugin.engineHint"),
      resizeResults: t("stacPlugin.resizeResults"),
      bands: t("stacPlugin.bands"),
      bandsPlaceholder: t("stacPlugin.bandsPlaceholder"),
      colormap: t("stacPlugin.colormap"),
      colormapDefault: t("stacPlugin.colormapDefault"),
      minValue: t("stacPlugin.minValue"),
      maxValue: t("stacPlugin.maxValue"),
      nodata: t("stacPlugin.nodata"),
      nodataPlaceholder: t("stacPlugin.nodataPlaceholder"),
      renderHint: t("stacPlugin.renderHint"),
      initialStatus: t("stacPlugin.initialStatus"),
      catalogInfo: (title, kind) => t("stacPlugin.catalogInfo", { title, kind }),
      zoom: t("stacPlugin.zoom"),
      add: t("stacPlugin.add"),
      download: t("stacPlugin.download"),
      adding: (asset) => t("stacPlugin.adding", { asset }),
      added: (asset) => t("stacPlugin.added", { asset }),
      addUnsupported: t("stacPlugin.addUnsupported"),
      addFailed: t("stacPlugin.addFailed"),
      addNoSourceLayers: t("stacPlugin.addNoSourceLayers"),
      cogUnsupported: t("stacPlugin.cogUnsupported"),
      formatCog: t("stacPlugin.formatCog"),
      formatGeoJson: t("stacPlugin.formatGeoJson"),
      formatPmtiles: t("stacPlugin.formatPmtiles"),
      formatParquet: t("stacPlugin.formatParquet"),
      formatZarr: t("stacPlugin.formatZarr"),
      formatUnknown: t("stacPlugin.formatUnknown"),
      addNoTarget: t("stacPlugin.addNoTarget"),
      addIcechunkFailed: t("stacPlugin.addIcechunkFailed"),
      zarrProblem: (problem) => t(ZARR_PROBLEM_KEYS[problem]),
      chooseTarget: t("stacPlugin.chooseTarget"),
      notAddable: t("stacPlugin.notAddable"),
    });
    setSamGeoLabels({
      panelTitle: t("samgeoPlugin.panelTitle"),
      intro: t("samgeoPlugin.intro"),
      apiUrl: t("samgeoPlugin.apiUrl"),
      checkConnection: t("samgeoPlugin.checkConnection"),
      notChecked: t("samgeoPlugin.notChecked"),
      checking: t("samgeoPlugin.checking"),
      connected: t("samgeoPlugin.connected"),
      unavailable: (error) => t("samgeoPlugin.unavailable", { error }),
      image: t("samgeoPlugin.image"),
      imageSource: t("samgeoPlugin.imageSource"),
      imageUpload: t("samgeoPlugin.imageUpload"),
      noRasterLayers: t("samgeoPlugin.noRasterLayers"),
      layerUnreadable: t("samgeoPlugin.layerUnreadable"),
      docsLink: t("samgeoPlugin.docsLink"),
      mode: t("samgeoPlugin.mode"),
      modeText: t("samgeoPlugin.modeText"),
      modePoints: t("samgeoPlugin.modePoints"),
      modeBox: t("samgeoPlugin.modeBox"),
      modeAutomatic: t("samgeoPlugin.modeAutomatic"),
      modelId: t("samgeoPlugin.modelId"),
      sam2ModelId: t("samgeoPlugin.sam2ModelId"),
      automaticHint: t("samgeoPlugin.automaticHint"),
      textPrompt: t("samgeoPlugin.textPrompt"),
      confidence: t("samgeoPlugin.confidence"),
      minSize: t("samgeoPlugin.minSize"),
      maxSize: t("samgeoPlugin.maxSize"),
      backend: t("samgeoPlugin.backend"),
      foregroundPoint: t("samgeoPlugin.foregroundPoint"),
      backgroundPoint: t("samgeoPlugin.backgroundPoint"),
      clickForeground: t("samgeoPlugin.clickForeground"),
      clickBackground: t("samgeoPlugin.clickBackground"),
      pointAdded: t("samgeoPlugin.pointAdded"),
      drawBox: t("samgeoPlugin.drawBox"),
      dragBox: t("samgeoPlugin.dragBox"),
      boxAdded: t("samgeoPlugin.boxAdded"),
      boxSummary: (box) => t("samgeoPlugin.boxSummary", { box }),
      noBox: t("samgeoPlugin.noBox"),
      pointSummary: (foreground, background) =>
        t("samgeoPlugin.pointSummary", { foreground, background }),
      pointsPerSide: t("samgeoPlugin.pointsPerSide"),
      predIou: t("samgeoPlugin.predIou"),
      stability: t("samgeoPlugin.stability"),
      clearPrompts: t("samgeoPlugin.clearPrompts"),
      promptsCleared: t("samgeoPlugin.promptsCleared"),
      segment: t("samgeoPlugin.segment"),
      chooseImage: t("samgeoPlugin.chooseImage"),
      enterPrompt: t("samgeoPlugin.enterPrompt"),
      addPoint: t("samgeoPlugin.addPoint"),
      drawBoxFirst: t("samgeoPlugin.drawBoxFirst"),
      segmenting: t("samgeoPlugin.segmenting"),
      noObjects: t("samgeoPlugin.noObjects"),
      added: (count, layer) => t("samgeoPlugin.added", { count, layer }),
      badResponse: t("samgeoPlugin.badResponse"),
      unknownProjection: t("samgeoPlugin.unknownProjection"),
    });
  }, [t]);
}
