import type { ProcessingModelGraph } from "@geolibre/core";
import { topologicalOrder, type DescriptorResolver } from "@geolibre/processing";

/** Render values accepted by Model Builder fields as deterministic Python literals. */
function pythonLiteral(value: unknown): string {
  if (value === null || value === undefined) return "None";
  if (typeof value === "boolean") return value ? "True" : "False";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "None";
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(pythonLiteral).join(", ")}]`;
  if (typeof value === "object") {
    return `{${Object.entries(value)
      .filter(([, item]) => item !== undefined)
      .map(([key, item]) => `${pythonLiteral(key)}: ${pythonLiteral(item)}`)
      .join(", ")}}`;
  }
  return pythonLiteral(String(value));
}

/**
 * Convert a validated Model Builder graph into a runnable GeoLibre notebook script.
 *
 * The script assumes `m` is the displayed Map containing the input layer ids.
 * Processing APIs add results to that map and return their ids; those ids carry
 * graph values into later calls just as Model Builder carries values over edges.
 */
export function modelGraphToPython(
  graph: ProcessingModelGraph,
  resolveDescriptor: DescriptorResolver,
): string {
  const ordered = topologicalOrder(graph);
  if (!ordered) throw new Error("Cannot generate Python for a model containing a loop.");

  const lines = [
    "# Generated by GeoLibre Model Builder.",
    "# Run after displaying `m`, with the model's input layers loaded in that map.",
    "",
  ];
  const values = new Map<string, Map<string, string>>();
  const incoming = new Map<string, typeof graph.edges>();
  for (const edge of graph.edges) {
    const list = incoming.get(edge.to) ?? [];
    list.push(edge);
    incoming.set(edge.to, list);
  }

  let inputIndex = 0;
  let stepIndex = 0;
  for (const node of ordered) {
    if (node.kind === "input") {
      inputIndex += 1;
      const variable = `input_${inputIndex}`;
      lines.push(`${variable} = ${pythonLiteral(node.layerId ?? "")}`);
      values.set(node.id, new Map([["out", variable]]));
      continue;
    }
    if (node.kind === "output") {
      const edge = incoming.get(node.id)?.[0];
      const source = edge ? values.get(edge.from)?.get(edge.fromPort) : undefined;
      if (source && node.name) lines.push(`m.rename_layer(${source}, ${pythonLiteral(node.name)})`);
      continue;
    }

    const descriptor = resolveDescriptor(node.provider, node.toolId);
    if (!descriptor || !node.toolId || !node.provider) {
      throw new Error(`Cannot generate Python for unknown tool "${node.toolId ?? ""}".`);
    }
    stepIndex += 1;
    const resultVariable = `step_${stepIndex}_result`;
    const parameters: Record<string, unknown> = { ...(node.parameters ?? {}) };
    const expressions = new Map<string, string>();
    for (const edge of incoming.get(node.id) ?? []) {
      const source = values.get(edge.from)?.get(edge.fromPort);
      if (source) expressions.set(edge.toPort, source);
    }

    const entries = Object.entries(parameters)
      .filter(([, value]) => value !== undefined && value !== "")
      .map(([key, value]) => [key, pythonLiteral(value)] as const);
    for (const [key, expression] of expressions) {
      const existing = entries.findIndex(([entryKey]) => entryKey === key);
      if (existing >= 0) entries[existing] = [key, expression];
      else entries.push([key, expression]);
    }
    const parameterLiteral = `{${entries
      .map(([key, value]) => `${pythonLiteral(key)}: ${value}`)
      .join(", ")}}`;
    const method = node.provider === "whitebox" ? "run_whitebox_tool" : "run_algorithm";
    lines.push(
      "",
      `${resultVariable} = m.${method}(${pythonLiteral(node.toolId)}, ${parameterLiteral})`,
    );

    const outputs = new Map<string, string>();
    descriptor.outputs.forEach((port, index) => {
      const variable = `step_${stepIndex}_${port.id.replace(/[^A-Za-z0-9_]/g, "_")}`;
      lines.push(`${variable} = ${resultVariable}["resultLayerIds"][${index}]`);
      outputs.set(port.id, variable);
    });
    values.set(node.id, outputs);
  }

  return `${lines.join("\n")}\n`;
}
