import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  GROWTH_ALLOWANCE,
  THRESHOLD,
  backendModulesWithoutTests,
  compareToBaseline,
  countLines,
  isExcludedPath,
  isGeneratedSource,
  parseLcovFiles,
  prunedBaseline,
} from "../scripts/check-untested-modules.mjs";

// `scripts/check-untested-modules.mjs` is the ratchet that keeps large modules
// with no test from hiding outside the coverage floor. These pin when it fails
// (a new untested file, a baseline file growing past its allowance) and when it
// only suggests shrinking the baseline.

const big = THRESHOLD + 100;

function compare(
  untested: Record<string, number>,
  baseline: Record<string, number>,
  options: { tested?: string[]; sizes?: Record<string, number> } = {},
) {
  return compareToBaseline({
    untested,
    baseline,
    tested: new Set(options.tested ?? []),
    sizes: options.sizes ?? { ...baseline, ...untested },
  });
}

describe("check-untested-modules compareToBaseline", () => {
  it("passes when every untested large file is in the baseline at its size", () => {
    const result = compare({ "apps/a/src/x.ts": big }, { "apps/a/src/x.ts": big });
    assert.equal(result.ok, true);
    assert.deepEqual(result.added, []);
    assert.deepEqual(result.grown, []);
    assert.deepEqual(result.removable, []);
  });

  it("fails on a new untested file over the threshold", () => {
    const result = compare({ "apps/a/src/new.ts": big }, {});
    assert.equal(result.ok, false);
    assert.deepEqual(result.added, [{ file: "apps/a/src/new.ts", lines: big }]);
  });

  it("ignores untested files at or under the threshold", () => {
    const result = compare({ "apps/a/src/small.ts": THRESHOLD }, {});
    assert.equal(result.ok, true);
    assert.deepEqual(result.added, []);
  });

  it("allows a baseline file to grow up to the allowance", () => {
    const file = "packages/p/src/y.ts";
    const result = compare({ [file]: big + GROWTH_ALLOWANCE }, { [file]: big });
    assert.equal(result.ok, true);
  });

  it("fails when a baseline file grows past the allowance", () => {
    const file = "packages/p/src/y.ts";
    const result = compare({ [file]: big + GROWTH_ALLOWANCE + 1 }, { [file]: big });
    assert.equal(result.ok, false);
    assert.deepEqual(result.grown, [{ file, lines: big + GROWTH_ALLOWANCE + 1, recorded: big }]);
  });

  it("suggests removing entries that gained a test, shrank under the threshold, or were deleted", () => {
    const baseline = {
      "apps/a/src/tested.ts": big,
      "apps/a/src/small.ts": big,
      "apps/a/src/gone.ts": big,
    };
    const result = compare({}, baseline, {
      tested: ["apps/a/src/tested.ts"],
      sizes: { "apps/a/src/tested.ts": big, "apps/a/src/small.ts": 200 },
    });
    // Shrinking the baseline never fails the check.
    assert.equal(result.ok, true);
    assert.deepEqual(result.removable, [
      { file: "apps/a/src/gone.ts", reason: "deleted" },
      { file: "apps/a/src/small.ts", reason: "small" },
      { file: "apps/a/src/tested.ts", reason: "tested" },
    ]);
  });

  it("records a shrunk entry so --prune can lower its count", () => {
    const file = "apps/a/src/x.ts";
    const result = compare({ [file]: big - 10 }, { [file]: big });
    assert.equal(result.ok, true);
    assert.deepEqual(result.shrunk, [{ file, lines: big - 10, recorded: big }]);
  });
});

describe("check-untested-modules prunedBaseline", () => {
  it("drops removable entries and lowers shrunk counts without adding anything", () => {
    const baseline = { "a.ts": 900, "b.ts": 800, "c.ts": 700 };
    const result = compare({ "b.ts": 750, "c.ts": 700, "new.ts": big }, baseline, {
      tested: ["a.ts"],
      sizes: { "a.ts": 900, "b.ts": 750, "c.ts": 700, "new.ts": big },
    });
    assert.deepEqual(prunedBaseline(baseline, result), { "b.ts": 750, "c.ts": 700 });
  });
});

describe("check-untested-modules helpers", () => {
  it("excludes declarations, barrels, locale catalogs, and colocated tests", () => {
    assert.equal(isExcludedPath("packages/core/src/index.ts"), true);
    assert.equal(isExcludedPath("apps/geolibre-desktop/src/vite-env.d.ts"), true);
    assert.equal(isExcludedPath("apps/geolibre-desktop/src/i18n/locales/en.ts"), true);
    assert.equal(isExcludedPath("packages/map/src/foo.test.ts"), true);
    assert.equal(isExcludedPath("apps/geolibre-desktop/src/lib/whitebox-menu-catalog.ts"), true);
    assert.equal(isExcludedPath("packages/core/src/store/index-helpers.ts"), false);
    assert.equal(isExcludedPath("packages/map/src/map-controller.ts"), false);
  });

  it("recognizes a generated-file header only near the top", () => {
    assert.equal(isGeneratedSource("// AUTO-GENERATED by a script\nexport {};\n"), true);
    assert.equal(isGeneratedSource("/** @generated */\n"), true);
    const late = `${"// line\n".repeat(20)}// AUTO-GENERATED\n`;
    assert.equal(isGeneratedSource(late), false);
  });

  it("counts lines like wc -l", () => {
    assert.equal(countLines(""), 0);
    assert.equal(countLines("a\nb\n"), 2);
    assert.equal(countLines("a\nb"), 2);
  });

  it("reads relative and absolute lcov SF entries as repo-relative paths", () => {
    const lcov = [
      "TN:",
      "SF:packages/core/src/a.ts",
      "end_of_record",
      "SF:/repo/apps/geolibre-desktop/src/b.tsx",
      "end_of_record",
    ].join("\n");
    assert.deepEqual(
      [...parseLcovFiles(lcov, "/repo")],
      ["packages/core/src/a.ts", "apps/geolibre-desktop/src/b.tsx"],
    );
  });

  it("matches backend modules to test_<module>.py and test_<module>_*.py", () => {
    assert.deepEqual(
      backendModulesWithoutTests(
        ["main", "vector", "whitebox", "sql"],
        ["test_vector.py", "test_whitebox_endpoints.py", "conftest.py", "test_sql.py"],
      ),
      ["main"],
    );
  });
});
