import assert from "node:assert/strict";
import { describe, it } from "node:test";
import type { ProcessingModelGraph } from "../packages/core/src/types";
import type { ModelToolDescriptor } from "../packages/processing/src/model-graph";
import { modelGraphToPython } from "../apps/geolibre-desktop/src/lib/model-python-script";

const tools: ModelToolDescriptor[] = [
  {
    key: "vector:buffer",
    provider: "vector",
    toolId: "buffer",
    name: "Buffer",
    group: "Vector",
    inputs: [{ id: "layer", label: "Layer", kind: "vector", required: true }],
    outputs: [{ id: "out", label: "Output", kind: "vector" }],
    parameters: [],
  },
  {
    key: "whitebox:split",
    provider: "whitebox",
    toolId: "split",
    name: "Split",
    group: "Raster",
    inputs: [{ id: "input", label: "Input", kind: "vector", required: true }],
    outputs: [
      { id: "first", label: "First", kind: "raster" },
      { id: "second", label: "Second", kind: "raster" },
    ],
    parameters: [],
  },
];

const resolve = (provider?: string, id?: string) =>
  tools.find((tool) => tool.provider === provider && tool.toolId === id);

describe("modelGraphToPython", () => {
  it("turns graph edges, parameters, providers, and output names into Python", () => {
    const graph: ProcessingModelGraph = {
      nodes: [
        { id: "source", kind: "input", x: 0, y: 0, layerId: "roads-layer" },
        {
          id: "buffer",
          kind: "tool",
          x: 0,
          y: 0,
          provider: "vector",
          toolId: "buffer",
          parameters: { distance: 100, dissolve: true, unused: "" },
        },
        {
          id: "split",
          kind: "tool",
          x: 0,
          y: 0,
          provider: "whitebox",
          toolId: "split",
          parameters: { threshold: null },
        },
        { id: "output", kind: "output", x: 0, y: 0, name: "Final result" },
      ],
      edges: [
        { id: "a", from: "source", fromPort: "out", to: "buffer", toPort: "layer" },
        { id: "b", from: "buffer", fromPort: "out", to: "split", toPort: "input" },
        { id: "c", from: "split", fromPort: "second", to: "output", toPort: "in" },
      ],
    };

    assert.equal(
      modelGraphToPython(graph, resolve),
      `# Generated by GeoLibre Model Builder.
# Run after displaying \`m\`, with the model's input layers loaded in that map.

input_1 = "roads-layer"

step_1_result = m.run_algorithm("buffer", {"distance": 100, "dissolve": True, "layer": input_1})
step_1_out = step_1_result["resultLayerIds"][0]

step_2_result = m.run_whitebox_tool("split", {"threshold": None, "input": step_1_out})
step_2_first = step_2_result["resultLayerIds"][0]
step_2_second = step_2_result["resultLayerIds"][1]
m.rename_layer(step_2_second, "Final result")
`,
    );
  });

  it("rejects cycles and unresolved tools", () => {
    const cyclic: ProcessingModelGraph = {
      nodes: [
        { id: "a", kind: "tool", x: 0, y: 0, provider: "vector", toolId: "buffer" },
        { id: "b", kind: "tool", x: 0, y: 0, provider: "vector", toolId: "buffer" },
      ],
      edges: [
        { id: "a-b", from: "a", fromPort: "out", to: "b", toPort: "layer" },
        { id: "b-a", from: "b", fromPort: "out", to: "a", toPort: "layer" },
      ],
    };
    assert.throws(() => modelGraphToPython(cyclic, resolve), /loop/);
    assert.throws(
      () =>
        modelGraphToPython(
          { nodes: [{ id: "x", kind: "tool", x: 0, y: 0, toolId: "missing" }], edges: [] },
          resolve,
        ),
      /unknown tool/,
    );
  });
});
